---

- hosts: default
  become: yes
  become_user: root
  tasks:
    - apt: update_cache=yes

    - name: install prerequisites
      apt: name={{ item }} state=present install_recommends=no
      with_items:
        # for remote execution of ansible files
        - acl
        # for yarn repository
        - apt-transport-https

    - name: install node prerequisites
      apt: name={{ item }} state=present install_recommends=no
      with_items:
        - libc-ares2

    # key: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    # sha256sum: 773b328f7b1d6db58a8c6a7fc89e2ed58ac5e06c3ab148411cf8272be7b1c472
    # see: https://deb.nodesource.com/setup_8.x
    - name: add nodesource apt-key
      apt_key: data={{ lookup('file', 'nodesource-repository.asc') }} state=present
      register: nodesource_apt_key

    - name: add nodesource repository
      apt_repository: repo='deb https://deb.nodesource.com/node_8.x {{ ansible_lsb.codename }} main' state=present filename='nodesource'
      register: nodesource_apt_repository

    # key: https://dl.yarnpkg.com/debian/pubkey.gpg
    # sha256sum: 9d9139d2e2075665ef35bdb6f32f750918fe18ce1c904d9316a42f614179daea
    - name: add yarn apt-key
      apt_key: id=1646B01B86E50310 data={{ lookup('file', 'yarn-repository.asc') }} state=present
      register: yarn_apt_key

    - name: add yarn repository
      apt_repository: repo='deb https://dl.yarnpkg.com/debian/ stable main' state=present filename='yarn'
      register: yarn_apt_repository

    - name: update apt cache
      apt: update_cache=yes
      when: nodesource_apt_key.changed or nodesource_apt_repository.changed or yarn_apt_key.changed or yarn_apt_repository.changed

    - name: install nodejs and yarn
      apt: state=latest name={{ item }} install_recommends=no
      with_items:
        - nodejs
        - yarn

    - name: install SASS
      apt: state=latest name={{ item }} install_recommends=no
      with_items:
        - sassc

    - name: PATH config
      copy: src=bashrc.local dest=~vagrant/.bashrc.local owner=vagrant group=vagrant mode=0640

    - name: install vue-cli globally
      shell: /usr/bin/yarn global add vue-cli
      args:
        creates: ~/.yarn/bin/vue
      environment:
        PATH: "/home/vagrant/.yarn/bin:{{ ansible_env.PATH }}"
      become_user: vagrant

    - name: install nginx-light
      apt: state=present name={{ item }} install_recommends=no
      with_items:
        - nginx-light

    - name: install nuxt nginx site
      copy: src=nginx/nuxt dest=/etc/nginx/sites-available/nuxt owner=root group=root mode=0640

    - name: enable nuxt nginx site
      file: state=link src=/etc/nginx/sites-available/nuxt dest=/etc/nginx/sites-enabled/nuxt
